name: KBOT-CICD

on:
  push:
    branches:
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: GitHub login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GIT_USERNAME }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build&push
        env:
          APP: "kbot"
          REGISTRY: ${{ vars.GIT_USERNAME }}
        run: make image push

  cd:
    name: CD
    needs: CI
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
          git push

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d cluster
        run: make create-cluster

      - name: Install ArgoCD
        run: make install-argocd

      - name: Expose ArgoCD (port-forward for CI)
        run: make port-forward-argocd

      