name: Setup K3D Cluster and Install ArgoCD

on:
  workflow_dispatch:

jobs:
  setup-k3d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d cluster
        run: make create-cluster

      - name: Install ArgoCD
        run: make install-argocd

      - name: Expose ArgoCD (port-forward for CI)
        run: make port-forward-argocd